# Generated by Django 5.1 on 2024-08-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Existing_Data',
            fields=[
                ('pattern_id', models.AutoField(primary_key=True, serialize=False, verbose_name='存在データパターンID')),
                ('category', models.BooleanField(default=False, verbose_name='カテゴリ')),
                ('grade', models.BooleanField(default=False, verbose_name='学年')),
                ('price', models.BooleanField(default=False, verbose_name='チケット料金')),
                ('seat_type', models.BooleanField(default=False, verbose_name='座席種別')),
                ('reasons', models.BooleanField(default=False, verbose_name='来場理由')),
                ('coupon', models.BooleanField(default=False, verbose_name='クーポン')),
                ('ticket_sale_date', models.BooleanField(default=False, verbose_name='チケット購買日')),
                ('past_visits', models.BooleanField(default=False, verbose_name='過去の来場')),
                ('play_sports', models.BooleanField(default=False, verbose_name='スポーツをする')),
                ('watch_sports', models.BooleanField(default=False, verbose_name='スポーツを見る')),
                ('country', models.BooleanField(default=False, verbose_name='国')),
                ('age', models.BooleanField(default=False, verbose_name='年齢')),
                ('affiliation', models.BooleanField(default=False, verbose_name='所属')),
                ('gender', models.BooleanField(default=False, verbose_name='性別')),
                ('occupation', models.BooleanField(default=False, verbose_name='職業')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': 'Existing_Data',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='イベントID')),
                ('name', models.CharField(max_length=255, verbose_name='イベント名')),
                ('team_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='チーム名')),
                ('opponent_team', models.CharField(blank=True, max_length=255, null=True, verbose_name='対戦相手')),
                ('game_date', models.DateField(blank=True, null=True, verbose_name='試合日')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='開場時間')),
                ('event_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='開催場所')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='チケット発売日')),
                ('data_version_date', models.DateTimeField(blank=True, null=True, verbose_name='データバージョン日')),
                ('number_of_spectators', models.IntegerField(blank=True, null=True, verbose_name='観客数')),
                ('existing_data_id', models.IntegerField(blank=True, null=True, verbose_name='存在データID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_image/', verbose_name='イベント画像')),
                ('description', models.TextField(blank=True, null=True, verbose_name='イベント詳細')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
