# Generated by Django 5.1 on 2024-08-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_event_data_version_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開演時間'),
        ),
    ]
