# Generated by Django 5.1 on 2024-08-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_event_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existing_data',
            name='age',
            field=models.BooleanField(default=False, verbose_name='年代'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='category',
            field=models.BooleanField(default=False, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='country',
            field=models.BooleanField(default=False, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='coupon',
            field=models.BooleanField(default=False, verbose_name='クーポン有無'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='past_visits',
            field=models.BooleanField(default=False, verbose_name='来場回数'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='play_sports',
            field=models.BooleanField(default=False, verbose_name='スポーツ実施頻度'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='price',
            field=models.BooleanField(default=False, verbose_name='チケット価格'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='reasons',
            field=models.BooleanField(default=False, verbose_name='知ったきっかけ'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='seat_type',
            field=models.BooleanField(default=False, verbose_name='座席種'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='ticket_sale_date',
            field=models.BooleanField(default=False, verbose_name='購入日'),
        ),
        migrations.AlterField(
            model_name='existing_data',
            name='watch_sports',
            field=models.BooleanField(default=False, verbose_name='スポーツ観戦頻度'),
        ),
    ]
