# Generated by Django 5.1 on 2024-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_existing_data_age_alter_existing_data_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='TSUKUBA LIVE!', max_length=255, verbose_name='イベント名'),
        ),
    ]
