# Generated by Django 5.1 on 2024-08-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='existing_data_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.existing_data', verbose_name='存在データID'),
        ),
    ]
